### ISSUE TITLE
Not able to install the latest version

### ISSUE THREAD

**Issue by Sakshi2022** [SheffieldML/GPy#1041]
<img width="560" alt="Screenshot 2023-10-28 at 12 50 15 PM" src="https://github.com/SheffieldML/GPy/assets/61898145/4359e1ed-1bd3-4112-acbe-a698b72b4cd3">
The repository says latest version is 1.12.0, however pip install is giving me the version 1.10.0 and even trying to install the version 1.12.0 by mentioning it specifically is giving the error shown in the image. How can I get the version 1.12.0? My current code is throwing error with version 1.10.0.

**Comment by MartinBubel** [comment]
Hi @Sakshi2022 
we are well aware of this, as well as the compatibility issues with numpy. I cannot promise that there will a new release by the end of the year as we have to deal with unmaintained dependencies etc. but we are trying our best to get a new release soon.
I will close your issue since it is already described in #1021  and probably also #1004.

**Comment by Sakshi2022** [comment]
Thanks a lot for reverting back on this! Your library has been very helpful
in our work.
