### ISSUE TITLE
Need pip package for 1.13

### ISSUE THREAD

**Issue by n3011** [SheffieldML/GPy#1057]
Currently, the 1.13 version is not available on pip. Can you please upload it.

**Comment by MartinBubel** [comment]
Hi @n3011 
thanks for raising attention on this. We are aware of this. We will soon provide the package on pypi.

**Comment by walsha2** [comment]
@MartinBubel Please also note that the tag in the repo is incorrect: `v.1.13.0`

There is an errant `.` after the `v`. Might be a good idea to publish the correct/expected repo tag: `v1.13.0`.

**Comment by MartinBubel** [comment]
Thanks for reporting @walsha2 !

In fact, we first need to patch `paramz`, as dependency of `GPy` before we can finally upload 1.13 to pypi. I will update tag 1.13.0 for now but most likely add a new 1.13.1 as soon as `paramz` is patched (we are talking about a couple more days here).

**Comment by MartinBubel** [comment]
Turns out I had to limit the maximum scipy version compared to v1.13.0, as linux and macos's python installed some pre-release scipy (even if it should not have done that...), which then caused some tests to break.

Thus, I did not upload v1.13.0 to pypi and directly moved to v1.13.1. There are wheels for windows (python 3.9 - 3.12), linux (python 3.9 - 3.12), and macos (python 3.10 - 3.12, as scipy wheels for macos python3.9 seem to be missing), as well as the source distribution.

I will close this issue. If the wheels are not working, please raise a new, dedicated issue.
