### ISSUE TITLE
why there is restriction on scipy version?

### ISSUE THREAD

**Issue by rameezdev** [SheffieldML/GPy#1066]
https://github.com/SheffieldML/GPy/blob/devel/setup.py#L150
conflict due to new release of scipy
https://pypi.org/project/scipy/#history

**Comment by MartinBubel** [comment]
Because `scipy` 1.12.0 requires NumPy 1.22.4 or greater. So far, we did not want to require such a "modern" release of `numpy`.

However, motivated by your issue, I digged into this a bit and it seems like there is something like [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html), which we should not ignore.

Probably gonna make a PR on this. If you need this fix asap, feel free to make a PR as it may take me a couple of days to find the time (even though it might not be much more than updating that one line in the setup.py ... but you never know).

**Comment by MartinBubel** [comment]
Closed via #1067
