### ISSUE TITLE
Predictive means and medians in GPy

### ISSUE THREAD

**Issue by lawrennd** [SheffieldML/GPy#107]
There seems to be a some confusion between median and mean in the likelihoods/GP model, this seems to lead to some bugs also.

The predictive_values aims to return mean, variance and 2.5% and 97.5% percentiles. In general, we might either choose to plot mean and standard error, or mean and confidence intervals (95%). But if you do the latter, then you should plot the median, not the mean, for the GP. In the Student-t likelihood (student_t.py), for predictive mean the *median* is implied by the comment where it says that the transforming the mu to return the predictive mean is 'only true if the link is monotonic'. 

https://github.com/SheffieldML/GPy/blob/params/GPy/likelihoods/student_t.py#L248-L249

This seems to be confusing the mean and the median. I think the confusion is encouraged by the same method predictive_values returning confidence intervals and percentiles, which are different things (apart from for Gaussian noise!). We should decide how to fix this.

**Comment by alansaul** [comment]
@lawrennd your right, at the moment the standard from plot_f() is to plot the mean and the 95% confidence intervals, where the median would make more sense. We have a function "predict_quantiles" that computes the quantiles via sampling, we could change the plotting code to do (2.5 50 97.5) and plot these. 
I'm not sure I understand your mention of the conditional_mean though, isn't this just the first moment? Since the student-t is symmetrical (regardless of the inverse link for used for f) won't the conditional mean always just be the transformation of f? I am more than likely mistaken!

**Comment by lawrennd** [comment]
For the student t it's OK ... but the comment is confusing as for others it
may not be ... and the mixing of mean and percentiles is ugly.

**Comment by jameshensman** [comment]
> The predictive_values aims to return mean, variance and 2.5% and 97.5% percentiles

I'm not sure this is right. Predictive values returns mean and variance, predictive_quantiles returns quantiles. Perhaps these have been overwritten for the specific case of Stu-T?

**Comment by mzwiessele** [comment]
We decided to have the 50th percentile and **Gaussian** variance of that returned by ```predict```.
`predict_quantiles` returns the given percentiles directly, for the given likelihood specific.
