### ISSUE TITLE
The possiblity of support numpy sparse matrix for normal GP

### ISSUE THREAD

**Issue by zhenwendai** [SheffieldML/GPy#128]
As mentioned by neil, if people apply GP to data with very sparse representation, e.g., text data, it would be very helpful if it can support sparse matrix format. Maybe we should investigate the possiblity of support sparse matrix for non-lvm models.

**Comment by dli1** [comment]
Hi all, 
Has this problem been solved?
Because I want to use sparse matrix in multi-output gaussian process model, to deal with text data.

**Comment by mzwiessele** [comment]
Unfortunately not.

We are using the numpy in-memory functionality to store only one copy of the overall parameter array. In order to alleviate this, we would need to rewrite the core parameter handling to support sparse matrices. 

There is some hope for the future, though. Numpy seems to get rid of the functionality to use the memory buffer of objects directly. This will be the point at which we need to change the core fundamentally. It will actually make the core a lot slower, as we will have to use either observers to keep the parameter array up-to-date, or use a split parameter array, which will be collected in every iteration. Both options are slow and will be run in pure python, whereas the current implementation is driven by the Fortran backend of Numpy.

Sad days for GPy users, hopefully we find another third option in time.

**Comment by dli1** [comment]
Hi Max,

Thank you very much for your quick and detailed reply!

Best,
Dan

**Comment by ekalosak** [comment]
Stale.
