### ISSUE TITLE
Problems with weave compilation?

### ISSUE THREAD

**Issue by jamesmcm** [SheffieldML/GPy#159]
Hi,

When running MRD, the optimisation is very slow and I receive the following message:

    Populating the interactive namespace from numpy and matplotlib creating /tmp/scipy-jamesmcm-RmXDOx/python27_intermediate/compiler_b567dc047844ab0fcb5f65882807d857    
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,    
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/jamesmcm/.cache/scipy/python27_compiled/sc_ba5041f28a3fb7cf0351b321232b44193.cpp:23:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
     /home/jamesmcm/.cache/scipy/python27_compiled/sc_ba5041f28a3fb7cf0351b321232b44193.cpp: In function ‘PyObject* compiled_func(PyObject*, PyObject*)’:
          /home/jamesmcm/.cache/scipy/python27_compiled/sc_ba5041f28a3fb7cf0351b321232b44193.cpp:743:43: error: no match for call to ‘(py::object) (int&, int&)’
                   retnd += tmp(n,q)*(X(n,d)-X2(q,d));
                                           ^
     /home/jamesmcm/.cache/scipy/python27_compiled/sc_ba5041f28a3fb7cf0351b321232b44193.cpp:743:51: error: no match for call to ‘(py::object) (int&, int&)’
                   retnd += tmp(n,q)*(X(n,d)-X2(q,d));
                                                   ^

     Weave compilation failed. Falling back to (slower) numpy implementation

I guess this is the cause of the slowness, but does anyone know how to fix this weave problem?

Thanks,
James

**Comment by a5a** [comment]
Hi,

I have been having this problem with the latest GPy (devel branch) in the past couple of months. When I ran weave.test('full') my tests all failed, so this may be a problem with weave rather than GPy?

I accidentally fixed my problem by importing setuptools before anything else and the weave tests completed without complaint. Importing setuptools at the top of my code seems to also fix the issue in GPy:

import setuptools
import GPy
[... the rest of my code ...]

I don't know why this fixed my problems, but maybe this workaround is helpful to others.

Cheers

Ahsan

**Comment by alansaul** [comment]
Hopefully this should be resolved now by moving from weave -> cython, if not please reopen this issue!
