### ISSUE TITLE
Implement Rprop as optimazation method

### ISSUE THREAD

**Issue by Luk0r** [SheffieldML/GPy#165]
I suggest to implement the Rprop algorithm for hyperparameter optimization.
I used
https://github.com/mblum/libgp
with my data and compared cg and rprop. In most (nearly all) cases rprop works better for me (lower log_likelihood, more relevant ARD).
My input data is 288 dims (but higly correlated) with n=46.
For me, rprop seems to better avoid local minima.

See also:
http://ml.informatik.uni-freiburg.de/_media/publications/blumesann2013.pdf

**Comment by jameshensman** [comment]
Hi @Luk0r , 

I'm not sure that specific optimization algorithms are within the scope of GPy. At the moment, we hook into the scipy.optimize routines for convenience. We also provide hooks so that you can get derivatives and plug into your favourite algorithm. I've successfully used these in conjunction with https://github.com/BRML/climin. 

If you'd like more information on how to get at these hooks, I'll gladly provide a quick IPython notebook. Let me know. 

James.

**Comment by Luk0r** [comment]
Thanks for ur reply.
I switchted to c++ and found a library with different optimization algorithms (https://github.com/PatWie/CppNumericalSolvers), which was easy to plug in the c++ code mentioned above.
Anyway I think it is also interesting for other people to see how this is working with hooks to plugin your own (or your mentioned) optimization algorithm.
So a python notebook would be very welcome :)

**Comment by mzwiessele** [comment]
Let me get to it, I will set up some notebook of how to implement an optimizer wrapper which works in GPy.

**Comment by mzwiessele** [comment]
Sorry for the delay, here is the notebook:
https://github.com/SheffieldML/notebook/blob/master/GPy/optimizer-implementation.ipynb

**Comment by Luk0r** [comment]
Didn't try for myself up to now, but anyway, many thanks, will help.
