### ISSUE TITLE
jitchol not working properly

### ISSUE THREAD

**Issue by adezfouli** [SheffieldML/GPy#175]
GPy/lilang/jitchol seems to raise exception: 

linalg.LinAlgError, "not positive definite, even with jitter.", 

even when jitter works.

**Comment by mzwiessele** [comment]
I have had this happen to me as well, has someone found as of why this
happens?

2015-02-14 13:09 GMT+00:00 Amir Dezfouli <notifications@github.com>:

**Comment by alansaul** [comment]
This is probably me and Neil, will take a look tomorrow! Weird as we had a
test for it!

Alan

**Comment by alansaul** [comment]
Has anyone got an example where this fails? It seems like to me it should
only fail if it has tried more than max_tries, otherwise if it is
successful it should return the Cholesky.

We did change this recently though as previously it logically appeared to
never successfully add jitter as your note suggests, it would continue
looping adding jitter but never returning upon success.
There is a test in linalg_test.py that tests it's boundary conditions, if
this is failing then we need to add a further test.

Cheers,

Alan

**Comment by adezfouli** [comment]
Thanks Alan for looking into it. I've installed GPy from pip, and seems it is not updated:

```
def jitchol(A, maxtries=5):
    A = np.ascontiguousarray(A)
    L, info = lapack.dpotrf(A, lower=1)
    if info == 0:
        return L
    else:
        diagA = np.diag(A)
        if np.any(diagA <= 0.):
            raise linalg.LinAlgError, "not pd: non-positive diagonal elements"
        jitter = diagA.mean() * 1e-6
        while maxtries > 0 and np.isfinite(jitter):
            try:
                L = linalg.cholesky(A + np.eye(A.shape[0]) * jitter, lower=True)
            except:
                jitter *= 10
            finally:
                maxtries -= 1
        raise linalg.LinAlgError, "not positive definite, even with jitter."
    import traceback
    try: raise
    except:
        logging.warning('\n'.join(['Added jitter of {:.10e}'.format(jitter),
            '  in '+traceback.format_list(traceback.extract_stack(limit=2)[-2:-1])[0][2:]]))
    import ipdb;ipdb.set_trace()
    return L
```

which does not return 'L'. Anyway, seems good now.

**Comment by alansaul** [comment]
Thanks for keeping a sharp eye Amir, we found that bug and squashed it this
week coincidentally this week!

Let us know if you find anything else odd.

Alan

**Comment by jameshensman** [comment]
Looks like this is fixed, closing.
