### ISSUE TITLE
LinAlgError: not positive definite, even with jitter

### ISSUE THREAD

**Issue by hahdawg** [SheffieldML/GPy#181]
I was trying to replicate the Mauna Loa C02 example from Rasmussen and Williams pg 118.  When I try to fit a model with a locally periodic kernel (see http://mlg.eng.cam.ac.uk/duvenaud/cookbook/index.html and http://dan.iel.fm/george/current/user/hyper/#sampling-marginalization), I get the LinAlgError.

Maybe I'm wrong, but I think, in GPy, the locally periodic kernel should be PeriodicExponential()*RBF().  If I don't try to multiply the kernels, everything seems to work fine.

My example is here:

https://github.com/hahdawg/gpy_example.

Thanks.

**Comment by jameshensman** [comment]
hi @hahdawg , 

I just ran this five times on the devel and master branches without failure. I recall that Neil made some recent improvements to the cholesky wrapper: perhaps these have fixed the issue?

If this persists after a git pull, let us have a fuller traceback and I'll have another look. 

Otherwise, please mark this bug closed, thanks.

James.

**Comment by hahdawg** [comment]
When I cloned it from git instead of using pip, everything worked.  Thanks.
