### ISSUE TITLE
GPHeteroscedasticRegression: RuntimeError: maximum recursion depth exceeded 

### ISSUE THREAD

**Issue by elkeschaper** [SheffieldML/GPy#187]
Dear all, 

I'm running into an error I wasn't able to fix when trying to create a new GPHeteroscedasticRegression model with the following input::

    import GPy
    import numpy as np
    X = np.array([[  3.,   2.],[  3.,   3.],[  3.,   4.],[  3.,   5.],[  3.,   6.],[  3.,   7.],[  3.,   8.],[  3.,   9.],[  3.,  10.],[  3.,  11.],[  3.,  12.],[  3.,  13.],[  3.,  14.],[  3.,  15.],[  3.,  16.],[  4.,   1.],[  4.,   2.],[  4.,   3.],[  4.,   4.],[  4.,   5.],[  4.,   6.],[  4.,   7.],[  4.,   8.],[  4.,   9.],[  4.,  10.],[  4.,  11.],[  4.,  12.],[  4.,  13.],[  4.,  14.],[  4.,  15.],[  4.,  16.],[  5.,   1.],[  5.,   2.],[  5.,   3.],[  5.,   4.],[  5.,   5.],[  5.,   6.],[  5.,   7.],[  5.,   8.],[  5.,   9.],[  5.,  10.],[  5.,  11.],[  5.,  12.],[  5.,  13.],[  5.,  14.],[  5.,  15.],[  5.,  16.],[  6.,   1.],[  6.,   2.],[  6.,   3.],[  6.,   4.],[  6.,   5.]])
    Y = np.array([[ 1.26009194],[ 1.11705572],[ 1.13733145],[ 0.90361428],[ 0.31151429],[-0.00558046],[-0.45493481],[-1.86474115],[-2.26985665],[-1.99614905],[-2.03313866],[ 0.14434941],[-0.85062491],[ 1.16469004],[ 1.08151982],[ 1.67174103],[ 1.1953489 ],[ 1.20362062],[ 0.91167117],[ 0.79200784],[ 0.12435543],[-0.66541966],[-0.3485895 ],[-2.39563241],[-2.08714596],[-1.99207315],[-2.17094947],[-0.0557339 ],[-0.29852262],[ 1.15457807],[ 0.9359406 ],[ 1.64350245],[ 1.06345797],[ 1.11817778],[ 0.61620098],[ 0.84620316],[ 0.19535039],[ 0.55819459],[-0.1007079 ],[-0.94839847],[-1.16807178],[-1.40530524],[-0.92938125],[ 0.86822105],[ 0.80256377],[ 0.84409863],[ 0.69201983],[ 1.64394879],[ 1.00750241],[ 1.09532067],[ 1.06837191],[ 0.86088544]])
    kernel = GPy.kern.RBF(X.shape[1], ARD=True)
    kernel += GPy.kern.White(X.shape[1])

This works::

    m = GPy.models.GPHeteroscedasticRegression(X[:-1,], Y[:-1,], kernel)

This fails::

    m = GPy.models.GPHeteroscedasticRegression(X, Y, kernel)
    
    
This is the (repetetive) error::

    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 964, in _name_changed
    self._remove_parameter_name(None, old_name)
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 961, in _remove_parameter_name
    self._connect_parameters()
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameterized.py", line 259, in _connect_parameters
    self._add_parameter_name(p, ignore_added_names=ignore_added_names)
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 940, in _add_parameter_name
    warn_and_retry(param, _name_digit.match(other.name))
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 935, in warn_and_retry
    param.name = match.group('name') + "_" + str(int(match.group('digit'))+1)
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameterized.py", line 315, in __setattr__
    object.__setattr__(self, name, val);
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 243, in name
    self._parent_._name_changed(self, from_name)
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 964, in _name_changed
    self._remove_parameter_name(None, old_name)
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 961, in _remove_parameter_name
    self._connect_parameters()
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameterized.py", line 259, in _connect_parameters
    self._add_parameter_name(p, ignore_added_names=ignore_added_names)
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 940, in _add_parameter_name
    warn_and_retry(param, _name_digit.match(other.name))
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 935, in warn_and_retry
    param.name = match.group('name') + "_" + str(int(match.group('digit'))+1)
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameterized.py", line 315, in __setattr__
    object.__setattr__(self, name, val);
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 241, in name
    self._name = name
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameterized.py", line 309, in __setattr__
    pnames = self.parameter_names(False, adjust_for_printing=True, recursive=False)
    File "/lib/python2.7/site-packages/GPy/core/parameterization/parameter_core.py", line 706, in parameter_names
    else: names = [adjust(x.name) for x in self.parameters]
    RuntimeError: maximum recursion depth exceeded

I've checked that the error is not related to the values of the last entries, but
rather to the lengths of X and Y...

I'm using GPy v.0.6.0 installed from Pypi.

Any idea what I'm doing wrong here?

Thanks a lot,

Elke

**Comment by mu2013** [comment]
I got similar error before. It seems the current setting only allow the
length of X or Y smaller than 50. I cannot remember exact limits.

but if you just want to assign fixed known error or variance to the
observed data point, Ricardo and Alan has provided a temporary solution but
just need to tune GPy a little bit:

Go to GPy/inference/latent_function_inference/exact_gaussian_inference.py
In line 48, add a flatten(), so that the line changes from:
diag.add(Ky, likelihood.gaussian_variance(Y_metadata))
to:
diag.add(Ky, likelihood.gaussian_variance(Y_metadata).flatten())

Then, you won't use the heteroscedastic model any more, but you will build
your model like this:

heteroscedastic_variance = np.array([....]) # Here you define your variances
g = GPy.likelihoods.Gaussian(variance=heteroscedastic_variance)
m = GPy.core.GP <http://gpy.core.gp/>(X=X, Y=Y,
kernel=GPy.kern.RBF(X.shape[1]), likelihood=g)

Now you fix the variance (you have to fix it, the model won't be able to
optimize it otherwise)
m.likelihood.variance.fix()

m.optimize() # Everything else should work as before.

cheers to Ricardo and Alan

**Comment by borislavsm** [comment]
@mu2013 
I tried your suggestion but I am experiencing problems with the predict function

I got the following error:
```
  File "/usr/local/lib/python2.7/dist-packages/GPy/core/gp.py", line 222, in predict
    mean, var = self.likelihood.predictive_values(mu, var, full_cov, Y_metadata)
  File "/usr/local/lib/python2.7/dist-packages/GPy/likelihoods/gaussian.py", line 88, in predictive_values
    var += self.variance
ValueError: operands could not be broadcast together with shapes (200,1) (100,1) (200,1) 
```

where the training is done on 200 samples and I want to make a prediction on 100 samples. 

Any suggestions how can I resolve that issue?

**Comment by mu2013** [comment]
The solution I suggested is just a temporary fix which you can use to get
the optimised kernel parameter. But if you already have the optimised
kernel parameter, you can write a bit of code to do the prediction which is
just conditional multi variant normal.
If you insist to use Heteroscedastic model to do prediction, Ricardo is the
expert.

cheers

**Comment by jameshensman** [comment]
@ric70x7 , could you take a look at this please?

**Comment by rocreguant** [comment]
Try:
kernel = GPy.kern.RBF(X.shape[1], ARD=True)
kern   =  kernel + GPy.kern.White(X.shape[1])
m = GPy.models.GPHeteroscedasticRegression(X, Y, kernel.copy())

The regression with kernels Fixed and White fails. Make sure to use the trained kernel.
Ref: https://github.com/SheffieldML/GPy/issues/196#issuecomment-114246090

**Comment by ric70x7** [comment]
Hi,

@borislavsm are you defining a new Y_metadata for the predictions? I would
need to see a piece of your code to be sure what is going on.

In any case, at the moment we don't have a routine to estimate new noise
terms for points outside the training set. Otherwise, for making
predictions at new points, it would be needed to pick a noise term from
those learnt in the training. Estimates of the latent variable at new
points are still available using m._raw_predict.
Cheers,

Ricardo



2015-08-17 15:24 GMT+01:00 Roc Reguant <notifications@github.com>:

**Comment by borislavsm** [comment]
Hi,

@ric70x7, I define a new Y_metadata for the predictions. I just fixed the new noise terms for the points outside of the training dataset but I agree that their estimation is an interesting problem. The code that I used:

```
import numpy as np
import GPy

Ns = 100
#Generate data
X = 10*np.random.random((Ns,1))
y = np.sin(X) + np.random.random((Ns,1)) - 0.5
Xtest = np.linspace(np.min(X), np.max(X), 121)
Xtest = Xtest[:,None]

# Estimate model
heteroscedastic_variance = np.random.random((X.shape[0],1)) # Here you define your variances
g = GPy.likelihoods.Gaussian(variance=heteroscedastic_variance)
m = GPy.core.GP(X=X, Y=y, kernel=GPy.kern.RBF(X.shape[1]), likelihood=g)
m.likelihood.variance.fix()
m.optimize()

# Make predictions
noise_dict = {'output_index':1*np.ones_like(Xtest).astype(int)}
ytest = m.predict(Xtest, Y_metadata=noise_dict)[0]
```

The error is :
```
ValueError: operands could not be broadcast together with shapes (121,1) (100,1) (121,1) 
```

Thanks

**Comment by ric70x7** [comment]
Ok, I see where the problem is. The Heteroscedastic model uses a different
kind of likelihood, than Gaussian, it is in essence a list of Gaussian
likelihoods -why is that? well at some point we might want to extend it to
a list of mixed noise models-.
When making predictions, this type of likelihood access each of the noise
terms through the Y_metadata dictionary. This does not happen with the
Gaussian likelihood that uses a vector of variances, not a single variance
term is extracted and there is when the incompatibility of the array shapes
appears.

So, the fastest solution at this point is the following:

ytest_mean, ytest_var = m._raw_predict(Xtest) # This is the prediction
of the latent variable (i.e., no noise added)

ytest_var += m.likelihood.variance[j] # Where y is the index of the
noise term you want to use.

Cheers,

Ricardo






2015-08-26 12:16 GMT+01:00 borislavsm <notifications@github.com>:

**Comment by mzwiessele** [comment]
Fixed, use the HeteroscedasticGaussian likelihood.
