### ISSUE TITLE
[devel] Adding kernels creates extra parameters.

### ISSUE THREAD

**Issue by Dapid** [SheffieldML/GPy#218]
Consider the following (in a heteroscedastic regression) running the lastest devel:

    import GPy
    import numpy as np
    kernel_homo = GPy.kern.Matern52(1) + GPy.kern.Matern32(1)
    kernel_fix = GPy.kern.Fixed(1, np.diag(np.abs(np.random.random(10))))
    kernel_fix.variance.fix()
    kernel = kernel_homo + kernel_fix

    print kernel_homo

I get (note the last line):

     add.               |  Value  |  Constraint  |  Prior  |  Tied to
    Mat52.variance     |    1.0  |     +ve      |         |         
    Mat52.lengthscale  |    1.0  |     +ve      |         |         
    Mat32.variance     |    1.0  |     +ve      |         |         
    Mat32.lengthscale  |    1.0  |     +ve      |         |         
    fixed.variance     |    1.0  |    fixed     |         |     

`kernel_homo` should not have the fixed component. It is interesting to add that this only happens if two basic kernels are added, but not if, for example, we set `kernel_homo = GPy.kern.Matern52(1)`.

**Comment by mzwiessele** [comment]
I was able to recreate, but need to label this wontfix for 0.8.

I will have a look if I find the time, there is definitely something unexpected happening. This is caused because the non-copy policy for taking in parameters (so that the kernels you add together can still be accessed from the outside variable used). 

Thanks for spotting that!
