### ISSUE TITLE
parallel optimize_restarts not working in devel

### ISSUE THREAD

**Issue by beckdaniel** [SheffieldML/GPy#283]
Hi all,

I installed the last devel version with this new paramz dependency and parallelizing optimize_restarts is not working, at least in my environment (Anaconda). Here is a gist showing what I have in IPython:

https://gist.github.com/beckdaniel/b24e4ed6496f1e58e550

Seems that something in the middle is not pickable but I am not sure exactly what...

**Comment by mzwiessele** [comment]
Yeah that is expected. It is using a pool of optimisers from the multiprocessing module and this is very unstable.

If you come up with a way of solving this, please put in a pull request, we are looking forward to a good solution to this.

**Comment by mzwiessele** [comment]
Have you found a way of how to do this?

@javiergonzalezh you had some ideas here?

**Comment by alexfeld** [comment]
So I'm looking into this as this would be very useful for me. There seem to be a couple bugs. First, the `GP.optimize()` method, which calls the `paramz.model.optimize()` function did not return the result of that function. The pickling issue is fixed by moving `opt_wrapper` in `paramz.model` out of the `optimize_restarts` method and into a module scope. However, I am now running into an issue with the returns of the wrapper function. I can output the `x_opt` and `f_opt` values but not the whole `Optimizer` object. Would this be ok? Is there anywhere in the code that relies on the value of `paramz.model.optimization_runs`?

**Comment by mzwiessele** [comment]
I think that should be ok, optimization runs is just a useful thing to have, i guess we should try make it optional anyway, as it will clutter the memory after a lot of runs...

**Comment by alexfeld** [comment]
Ok, great. I actually figured out what was wrong. I'm pushing fixes for this now.

Alex




On Fri, Mar 17, 2017 at 6:50 PM -0400, "Max Zwiessele" <notifications@github.com> wrote:










I think that should be ok, optimization runs is just a useful thing to have, i guess we should try make it optional anyway, as it will clutter the memory after a lot of runs...

**Comment by alexfeld** [comment]
GPy fix in #491

**Comment by alexfeld** [comment]
`paramz` fix in  sods/paramz#16
