### ISSUE TITLE
For multidimensional models, fixing only parameters of certain dimensions?

### ISSUE THREAD

**Issue by elkeschaper** [SheffieldML/GPy#299]
A question on [interacting with models](https://github.com/SheffieldML/GPy/blob/master/doc/tuto_interacting_with_models.rst):
Given a multidimensional model:

`ker = GPy.kern.StdPeriodic(input_dim=2, ARD1=True)`

In this example, it is possible to fix both wavelength parameters:
`ker.wavelengths.fix((2,5))`

Also, it is possible to unfix them:
`ker.wavelengths.unfix()`

Now, is it also possible to fix only one wavelength parameter? 
Is there a difference between the _fix()_ and the _constrain_fixed()_ methods? 

Thanks a lot, best,

Elke

**Comment by mzwiessele** [comment]
1.) Yes you just select the exact wavelength you want to fix:

ker.wavelengths[0, [0]].fix()

2.) fix is a proxy for constrain_fixed

**Comment by elkeschaper** [comment]
> 1.) Yes you just select the exact wavelength you want to fix:
> 
> ker.wavelengths[0, [0]].fix()

This does not seem to work for me:

> > > ker = GPy.kern.StdPeriodic(input_dim=2, ARD1=True)
> > > ker.wavelengths[0, [0]].fix()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File “/my/path/to/python3.5/site-packages/paramz/param.py", line 164, in **getitem**
> > >     new_arr = super(Param, self).**getitem**(s, _args, *_kwargs)
> > > IndexError: too many indices for array

My Environment:
paramz==0.1.2
GPy==0.9.6
Python=3.5.0

Perhaps a Python3 issue? 
Or syntax problems?

> 2.) fix is a proxy for constrain_fixed

Thank you for clarification!

**Comment by mzwiessele** [comment]
You need to select the one wavelength you want exactly. Now the params are Numpy arrays, so you need to use the right indexing for the selection, as: if you just choose one wavelength directly you get back a float. Thus, you want to use advanced indexing (see numpy advanced indexing) in order to keep one dimension. That is why there is two brackets [[]]. Now it depends on the dimensions of the wavelengths of how to slect them. I somehow assumed they are two dimensional, which does not make sense... 

You'll figure it out from here, just select the one lengthscale you want and try printing it. If it prints the Param object (nice printing with constraints and so on) it is right. You can call any of the constraints methods on Param and Parameterized objects.

Best

**Comment by elkeschaper** [comment]
Thank for the helpful explanation, Max!
Here’s an example where the wavelength parameter for the 3rd input dimension is fixed to 42:

ker = GPy.kern.StdPeriodic(input_dim=3, ARD1=True)
ker.wavelengths[2] = 42
ker.wavelengths[[2]].fix()
print(ker.wavelengths)
