### ISSUE TITLE
Mean function for sparse GP regression?

### ISSUE THREAD

**Issue by jluttine** [SheffieldML/GPy#337]
`GPRegression` accepts `mean_function` keyword argument but `SparseGPRegression` doesn't take any arguments related to a mean function. I find this confusing and inconsistent. Could `mean_function` be added as a keyword argument in `SparseGPRegression` as well? Is there currently some other way to specify the mean function for `SparseGPRegression`? Now I just add it like `model.mean_function = mean_function` after creating the `SparseGPRegression` object. However, I'm not sure if this is a proper way to do it, and anyway I'd like to see the keyword argument in the constructor. :yum:

**Comment by jluttine** [comment]
If it as simple as just adding the given `mean_function` as a member attribute to the object, I can make a pull request myself. But if `SparseGPRegression` lacks support for mean function in the computations, then it's a bit bigger task.

**Comment by mzwiessele** [comment]
I'm not sure actually but I seem to remember there where some issues with it. I haven't checked but is it in the devel branch, maybe?

**Comment by alansaul** [comment]
At the moment we only have parameterized mean functions implemented for straight-forward GP regression. If your mean function is known beforehand (i.e. you know it is np.pow(X,2)), I believe you can just do Y = Y - np.pow(X,2) before fitting the model, your GP will then be over the residuals. If it is parametric and you wish to learn it along side the GP parameters (which I suspect you do), more work needs to be done unfortunately yes.

For the sparse GP case, you would need:
1. To figure out what 'dL_dm' (the gradient of the bound with respect to the mean_function m) is for the inference/latent_function_inference/var_dtc.py inference method.
2. Add 'dL_dm' to the grad_dict of var_dtc - as in inference/latent_function_inference/exact_gaussian_inference.py code.
3. In parameters_changed in sparse_gp.py, add an update to the gradients of the mean function, as it is in core/sparse_gp.py
4. Add the mean_function to the arguments of sparse_gp as you said, and add the mean function as a parameter:

```
        #handle the mean function
        self.mean_function = mean_function
        if mean_function is not None:
            assert isinstance(self.mean_function, Mapping)
            assert mean_function.input_dim == self.input_dim
            assert mean_function.output_dim == self.output_dim
            self.link_parameter(mean_function)
```

I haven't looked at calculating dL_dm for sparse GP's, but I imagine that might not be _too_ difficult. The code for var_dtc.py can be a little cryptic due to the effort we have put into optimizing it for speed and generalization. If you wish to do it for uncertain inputs (so we can have mean functions in the BGPLVM for example), I believe it would be more tricky though I haven't looked at it. 

The same applies if anyone wants to implement any other approximation with a mean function, for example Laplace and EP, as we didn't implement mean functions for these when we initially implemented them.

**Comment by jluttine** [comment]
Thanks for the detailed response! As a simple workaround, I just optimized the mean function parameters separately using scipy.optimize with squared error cost, and then fitting GP to the residuals.

**Comment by mzwiessele** [comment]
Are you willing to implement the mean function for sparse GPs? Otherwise I will close : )
