### ISSUE TITLE
Imposible to set fixed mean function

### ISSUE THREAD

**Issue by Vichoko** [SheffieldML/GPy#391]
Hello, i'm trying to make a GP over a 2-dimensional dataset. 
My objective is to **visualize different mean functions** (Constant, linear, cuadratic, etc) with a fixed kernel function (RBF in this example)

I have this simple code that defines a mean function by defining Mapping with a lambda function that returns 0 (Constant function). This to try to **fix a mean function for the model**:

```
data = pd.read_csv("./data.out"," ")

X = data.as_matrix(columns=['x'])
Y = data.as_matrix(columns=['y'])

mf = GPy.core.Mapping(1,1)
mf.f = lambda x:0
mf.update_gradients = lambda a,b: 0
mf.gradients_X = lambda a,b: 0

k = GPy.kern.RBF(1)
lik = GPy.likelihoods.Gaussian()
m = GPy.core.GP(X, Y, kernel=k, likelihood=lik, mean_function=mf)

m.plot()
matplotlib.pylab.show(block=True)
```

The thing is that by doing this, GP method modify the mean function of the model to fit the data in a very no-constant way; like can be seen here:
[Plot](http://i.imgur.com/aHVs05B.png)
(It starts and ends in 0; but fits the data)

The same thing happens when i define a linear function for the mapping; the model returns a no-linear mean function after the process.

I'm not sure if this is an error. Or maybe the feature i'm looking isn't covered by this framework.
Anyway i prefer to submit this issue because i couldn't find any other related to this matter; and maybe this can help other people in the future.

**Comment by abaisero** [comment]
If I understand your issue correctly, you seem to be expecting that the posterior mean should be 0. The mean function that you feed into the model is the _prior_ mean function, not a hard-coded posterior mean function.  You can't force the posterior mean function to be whatever you wish it to be: by the very nature of GP models, the posterior mean is a function of the observations.

Verify this by setting `mf.f = lambda x: k` for different values of k.  You'll notice that the function's posterior mean will be `k` far from the observations (where the prior mean has a larger effect on the posterior given the non-existent observations), but it will still adapt to the observations in the area where these are.

The non-linearity of the posterior is due to the kernel function, not the prior mean.  While you can't set a fixed posterior mean, you can enforce certain properties of the posterior mean (e.g. linearity) by using different types of kernels.  To enforce linearity, just use a linear kernel (rather than RBF). Notice that although you enforced linearity this way, the actual function values still adapt to the actual observations made.

**Comment by Vichoko** [comment]
Thank you bigblindbais for you responce; now it's very clear to me that i was seeing it wrong hehe. 
But now i understand that it was my error of understanding what GP means.
Thanks also for explaining the correct way, i get i now :) :+1:
