### ISSUE TITLE
unoptimized behavior of SVGP 

### ISSUE THREAD

**Issue by vahidbas** [SheffieldML/GPy#393]
When using a GP for prediction, even without optimization I expect it should return something close to the given mean function. However this is not the case for SVGP considering this code

``` python
import numpy as np
import GPy

X = Z = np.arange(0, 1, 0.2).reshape(-1, 1)
Y = X

kernel = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)
lik = GPy.likelihoods.Gaussian()

m1 = GPy.core.GP(X, Y, kernel, lik, mean_function=GPy.mappings.Identity(1, 1))
m2 = GPy.core.SparseGP(X, Y, X, kernel, lik, mean_function=GPy.mappings.Identity(1, 1))
m3 = GPy.core.SVGP(X, Y, X, kernel, lik, mean_function=GPy.mappings.Identity(1, 1))

f1, _ = m1.predict_noiseless(X)
f2, _ = m2.predict_noiseless(X)
f3, _ = m3.predict_noiseless(X)

np.set_printoptions(precision=3)
print f1.T
print f2.T
print f3.T
```

The core GP returns 

```
[[ 0.   0.2  0.4  0.6  0.8]]
```

which is exactly what expected.

The SparseGP returns

```
[[ 0.214  0.48   0.741  0.989  1.219]]
```

seems has a constant bias of 0.2 but close enough for me.

But surprisingly the SVGP returns 

```
[[  1.421e-14   3.270e-14   6.539e-14   4.841e-14   2.887e-15]]
```

almost zero! It totally ignores the mean function in the prediction.

I checked it after optimization and it gives correct results.But iti doesn't mean that it takes into account the mean function because the variational distribution can capture the effect mean function during optimization.

I tried also to see where the issue starts. I found out that for SVGP this function 

``` python
mu, var = self.posterior._raw_predict(...)
```

returns exactly the negative of mean function then when adds to it makes everything zero. 

Can anybody shed some light on this issue?

Thanks
Vahid

**Comment by mzwiessele** [comment]
Could you try making copies of lik kern and any other parameters you put into the models. GPy supports paramteres to be manipulated outside its models and may not be copied.

**Comment by vahidbas** [comment]
Ok, I fed copies of parameters to the models, but still getting same result. Even trying SVGP alone gives me zeros.

**Comment by alansaul** [comment]
Hi Vahid, I believe I have an answer for this.

The problem is that you are not optimising the variational parameters for q(u) when doing SVGP. As the mean of q(u) is zero (the default). If you fix the other parameters and optimise q(u) to the optimal values it will do as expected.

I believe the reason for sparse_gp results being different is that the mean function is in fact being ignored (silently, which isn't great!). If you look at sparse_gp.py parameters_changed the inference method is never passed self.mean_function, and the code in inference/latent_function_inference/var_dtc.py (which is the inference engine for sparse_gp) explicitly asserts the mean function is None. We should be passing the mean function to self.inference_method.inference, and then the assert would appear.

See the below code for an example when the mean_function is not used (identity doesn't appear to be in the devel versions GPy/mappings/**init**.py anymore, @mzwiessele / @mikecroucher, any idea why this is?). 

This is without a mean function:

```
import numpy as np
import GPy

X = Z = np.arange(0, 1, 0.2).reshape(-1, 1)
Y = X

kernel = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)
lik = GPy.likelihoods.Gaussian()

m1 = GPy.core.GP(X, Y, kernel, lik)
m2 = GPy.core.SparseGP(X, Y, X, kernel, lik)
m3 = GPy.core.SVGP(X, Y, X, kernel, lik)

# Fix everything except q(u) and optimize q(u)
m3.fix()
m3.q_u_mean.unfix()
m3.q_u_chol.unfix()
m3.optimize('bfgs', max_iters=2000, messages=1)

f1, _ = m1.predict_noiseless(X)
f2, _ = m2.predict_noiseless(X)
f3, _ = m3.predict_noiseless(X)

np.set_printoptions(precision=3)
print f1.T
print f2.T
print f3.T
```

This is with:

```
import numpy as np
import GPy

X = Z = np.arange(0, 1, 0.2).reshape(-1, 1)
Y = X

kernel = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)
lik = GPy.likelihoods.Gaussian()

# You need to add 'from .identity import Identity' to mappings/__init__.py if you have the latest GPy.
m1 = GPy.core.GP(X, Y, kernel, lik, mean_function=GPy.mappings.Identity(1, 1))
m2 = GPy.core.SparseGP(X, Y, X, kernel, lik, mean_function=GPy.mappings.Identity(1, 1))
m3 = GPy.core.SVGP(X, Y, X, kernel, lik, mean_function=GPy.mappings.Identity(1, 1))

# Fix everything except q(u) and optimize q(u)
m3.fix()
m3.q_u_mean.unfix()
m3.q_u_chol.unfix()
m3.optimize('bfgs', max_iters=2000, messages=1)

f1, _ = m1.predict_noiseless(X)
f2, _ = m2.predict_noiseless(X)
f3, _ = m3.predict_noiseless(X)

np.set_printoptions(precision=3)
print f1.T
print f2.T
print f3.T
```

**Comment by mzwiessele** [comment]
No the import of the Identity is a pkg bug and should be added in.

**Comment by ekalosak** [comment]
Stale.
