### ISSUE TITLE
Add Spectral Mixture Kernel

### ISSUE THREAD

**Issue by cdipaolo** [SheffieldML/GPy#401]
It would be a good idea, I think, to add in the [spectral mixture (SM) kernel](http://hips.seas.harvard.edu/files/wilson-extrapolation-icml-2013_0.pdf) introduced by Andrew Wilson and Ryan Adams in 2014. There's been a decent literature based on this work (over 60 citations in 2 years) including some work I'm starting on and it'd be helpful to not have to hand roll GP optimization every time I use this kernel.

I looked around the list of currently implemented kernels and couldn't find it but if I just missed it let me know.

I guess the broader question here is how close you want this package to follow the literature. `sklearn`, for example, has a policy of _not_ closely following the literature, so that's not necessarily a bad thing, but it'd be helpful to have a guideline on what the package's goals are in this domain.

Let me know what you guys think. Thanks 😀 !

(I'd be willing to help out in adding this though I'm not as of yet familiar with the internals of the package)

**Comment by lawrennd** [comment]
Hi Conner,

We welcome contributions, so please feel to add it.

I once did a test run of that covariance function by building covariance
functions from cosine, squared exponential using product and additive
covariance functions, but it's likely the case that a specific
implementation would be more efficient.

Neil
On 19 Jun 2016 21:50, "Conner DiPaolo" notifications@github.com wrote:

It would be a good idea, I think, to add in the spectral mixture (SM) kernel
http://hips.seas.harvard.edu/files/wilson-extrapolation-icml-2013_0.pdf
introduced by Andrew Wilson and Ryan Adams in 2014. There's been a decent
literature based on this work (over 60 citations in 2 years) including some
work I'm starting on and it'd be helpful to not have to hand roll GP
optimization every time I use this kernel.

I looked around the list of currently implemented kernels and couldn't find
it but if I just missed it let me know.

I guess the broader question here is how close you want this package to
follow the literature. sklearn, for example, has a policy of _not_ closely
following the literature, so that's not necessarily a bad thing, but it'd
be helpful to have a guideline on what the package's goals are in this
domain.

Let me know what you guys think. Thanks 😀 !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/SheffieldML/GPy/issues/401, or mute the thread
https://github.com/notifications/unsubscribe/AAIKWlUKKZK3U7N5-TfB7fOLct06e511ks5qNat1gaJpZM4I5P8X
.

**Comment by mzwiessele** [comment]
Have a look at https://gpy.readthedocs.io/en/deploy/tuto_creating_new_kernels.html where we explain how to implement a new kernel.

**Comment by cdipaolo** [comment]
Oh that's super helpful thank you! I started working on it but ended ups
pending a day discovering everything in that document by reading the source
for other kernels haha.

Currently I'm just trying to come up with a clever way to vectorize the
kernel function.

**Comment by mathDR** [comment]
@cdipaolo If you haven't already implemented this kernel, you can see my implementation in pyGPs: https://github.com/marionmari/pyGPs/blob/master/pyGPs/Core/cov.py  line 453

It may prove helpful

**Comment by cdipaolo** [comment]
@mathDR I've been pretty swamped with work so I haven't had as much time to work on this as I'd like but I have a first pass [here](https://github.com/cdipaolo/GPy/blob/devel/GPy/kern/src/spectral_mixture.py). I'm pretty sure the actual computation is working but I think there may be some issues with the gradient computations (basically it just doesn't optimize and some gradients diverge; this may be an issue with my understanding of the API for gradient computation or a bug in some segment of the code).

Thanks for your reference though I appreciate it! I'm not sure how much the derivative code will assist with debugging given the different interface but I'll see if it can mesh well.

**Comment by mzwiessele** [comment]
Any updates on this? We are looking forward to the spectral mixture kernel: )

**Comment by cdipaolo** [comment]
@mzwiessele Just got unswamped with work so I'm going to try and get this out. I was having issues with optimizing the kernel params so I just added [tests](https://github.com/cdipaolo/GPy/blob/devel/GPy/testing/spectral_mixture_tests.py) to make sure the forward pass was correct -- it is. It looks like I'll be spending a couple hours debugging gradients (this always happens, doesn't it? 😄 ).

Ironically when I was writing the tests I was using the original paper as the implementation to test on and not the [correction to the typo](http://www.cs.cmu.edu/~andrewgw/typo.pdf) so they initially failed before I realized the implementation was correct all along.

Before I push out the change I'm going to try and replicate the results from the original paper on the CO2 data in an ipython notebook and link that here.

**Comment by mzwiessele** [comment]
great stuff, how are you coming along?

**Comment by cdipaolo** [comment]
@mzwiessele just started school again so I can't currently work on it -- basically it seems that there are some issues with the gradients because optimization won't succeed in some manual tests (reproducing paper results -- definitely a problem with the code not the paper). That seems interesting because I included the kernel in the gradient checking tests and those pass so I'm out of my league in terms of knowing where the issue would be.

**Comment by lawrennd** [comment]
There can be quite serious issues with initialization with these kernels,
certainly when I implemented them I had such issues. Any kernel with
periodicity (in my experience) can have fairly major problems. It might be
worth checking if this is the problem in your case.

**Comment by NoahSlv** [comment]
Hi,

Just checking in to see if any new code is available for this.  @cdipaolo any chance you can push the latest?

**Comment by cdipaolo** [comment]
@NoahSlv just pushed what I had been working on about a month ago.

**Comment by mathDR** [comment]
@lawrennd Have you come across any insight into initializing kernels with periodic components?  I am running into issues with another type of periodic kernel and wondered if you had any insight.

**Comment by lawrennd** [comment]
Tough one, period has multiple local minima.

Which kernel?

**Comment by jorgeloaiza** [comment]
Hello.
Is already  The Spectral Mixture kernel in GPy?

**Comment by imsrgadich** [comment]
@cdipaolo were you able to find the issues with the initializations?

**Comment by imsrgadich** [comment]
for people interested I have SM kernel in GPflow. 

https://github.com/imsrgadich/gprsm
