### ISSUE TITLE
predict method for poisson regression only yields zeros

### ISSUE THREAD

**Issue by ltalluto** [SheffieldML/GPy#414]
I am getting bizarre results when trying to run a GP regression with a Poisson likelihood. I first followed the tutorial here:
[http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/Poisson%20regression%20tutorial.ipynb](http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/Poisson%20regression%20tutorial.ipynb)
This works exactly as expected. I then tried to adapt the code to my own data. Below a test plot. The confidence bands appear as expected, but the mean weirdly drops to zero in the middle. Using the predict method gives similar results; 0 mean and variance in the same neighborhood as shown on the plot.

![figure_1](https://cloud.githubusercontent.com/assets/5796287/17254670/11d19bf6-55b6-11e6-81de-2ae9f7c089e8.png)

Here's a reproducible example, with a similar plot. In this case, I get zeros throughout the prediction range. Am I missing something obvious here?

```
%pylab osx
import numpy as np
import pylab as pb
import GPy

numpy.random.seed(0)
X = np.random.normal(0,1,(75,1))
Y = np.random.poisson(30 + 2*X,(75,1))
kernel = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)
poisson_likelihood = GPy.likelihoods.Poisson()
laplace_inf = GPy.inference.latent_function_inference.Laplace()
m = GPy.core.GP(X=X, Y=Y, likelihood=poisson_likelihood, inference_method=laplace_inf, kernel=kernel)
m.optimize()
m.plot()
```

![figure_2](https://cloud.githubusercontent.com/assets/5796287/17254795/9371a5b6-55b6-11e6-9c76-6ec8649d0ab0.png)

**Comment by ric70x7** [comment]
Hi Matthew,
You are not missing anything obvious. This is a numerical problem with the
way the predictive mean and predictive variance are computed. The
quadrature to compute these statistics is not an easy task and in some
cases variance estimate go very large and this pulls the expected value to
zero... I've spend a good time trying to solve the same issue with the EP
approximation, but I haven't been able to come up with a satisfactory
solution.
You don't see this problem in the confidence bars because the are being
computed by sampling, not by numerical integration.
I would recommend you to generate samples and compute the mean and variance
by separate.
Just be sure that the number of samples is large enough... it can be slow,
but it should work.

Ricardo

2016-07-29 9:03 GMT-07:00 Matthew Talluto notifications@github.com:

**Comment by mikecroucher** [comment]
Hi

This is interesting.
What, exactly, is the problem with the numerical quadrature?

Would it be possible to isolate an example problem integrand?

Cheers,
Mike

**Comment by ltalluto** [comment]
You guys are fast! Sampling will work for now (and makes intuitive sense to me, coming from an MCMC background). Obviously it's less ideal when the problem gets large. I'm probably in way over my head as far as resolving the problem goes, but if I can help in some way, let me know!

Cheers,
Matt

**Comment by ric70x7** [comment]
Hi Mike,
In some cases the density function to be integrated is quite sharp. Then
the points in the quadrature miss the area with "substantial" density, and
hence the computed value is zero.
I'll work on an example and get back to you.
Cheers,
Ricardo

2016-07-29 11:58 GMT-07:00 Matthew Talluto notifications@github.com:
