### ISSUE TITLE
euclidian distance for RBF kernel not handling properly small distances

### ISSUE THREAD

**Issue by updiversity** [SheffieldML/GPy#444]
Hi,

I have tried to build a gaussian process model, using an RBF kernel. My input data have a mean around 10**12 and a variance of 100.

I got problem with the Cholesky matrix computation, but it looks like the problem is during the scaling operation when the Covariance matrix is computed.  The Euclidian distance gets rounded to 0.0. as you can see with the following test : 

```
import GPy
k1 = GPy.kern.RBF(input_dim=1,variance=1.)
k1._scaled_dist(X=np.array([[10e12],[10e12+100.]]))[0,1]

0.0
```

while the standard scipy method give me the right result:

```
sp.spatial.distance.euclidean([10e12],[10e12+100])

100.0
```

Does it mean I should scale first my inputs before to use GPy ?

**Comment by mzwiessele** [comment]
You can scale your data using gpy. Just give normalizer=True as an argument in your model creation and it should work fine. It is always good to scale your data, as the assumption of GPs usually involves a mean of zero.

**Comment by lawrennd** [comment]
It looks like the large values are on the inputs rather than the targets
Max (do I understand correctly). Does normalizer=True also cover inputs?
The mean zero assumption doesn't apply to the inputs (for a stationary
covariance, in theory it doesn't matter the mean, but in practice it will
create significant numerical issues to work with such large values!!!).

Neil

**Comment by mzwiessele** [comment]
Indeed perfectly right, the inputs do NOT get scaled by the normalizer.

**Comment by zhenwendai** [comment]
I think the underlying reason is that you are really working on the edge 
of double precision. The relative difference of your two values is 1e-11 
and the hardware limit is between 1e-14 and 1e-15.

In GPy, we take a more computationally efficient approach but not 
numerically as accurate. I would suggest you do a zero mean 
normalization for your input values if possible.

Zhenwen

**Comment by updiversity** [comment]
Thanks for the replies. At the moment by scaling my inputs I have been able to use GPy. 

Investigating a bit, on the code, it looks like the rounding is occurring within the tdot function.
