### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jlintusaari** [SheffieldML/GPy#451]
Hi,

we would like to use GPy as a dependency in our project. The only problem is the prerequisite to have scipy installed before you can install GPy. This prevents direct installation with pip and is somewhat clumsy. Would be much better if installation didn't depend on scipy. Would you be able to change this?

**Comment by kskyten** [comment]
I think it is a bootstrapping problem with setup.py importing numpy to find numpy header files in lines 85-105 rather than a problem with scipy.

```
pip install GPy
```

doesn't work if numpy is not installed.

**Comment by javdrher** [comment]
Hi, I am encountering the numpy error myself as we added GPy as a dependency. This could be resolved by adding 
setup_requires=['numpy']
to setup.py
It seems this doesnt actually install numpy on the system, but it drags it in to be able to run setup.py. 

edit: nope, it only seems to work when running python setup.py install, trying to find out if this is possible after all

**Comment by lawrennd** [comment]
@mzwiessele?

**Comment by mzwiessele** [comment]
We have install_requires, is there a difference?

**Comment by javdrher** [comment]
setup_requires is used to preload things and doesnt seem to install to site-packages, it typically contains for instance nose, so you can run tests without actually installing nose as a dependency. It seems mostly related to running setup.py directly, rather than using pip.

For GPy setup_requires and install_requires do not help because it already fails before it even gets there. Numpy is effectively a dependency of setup.py (which resolves dependencies). I googled this a bit and several libraries have similar issues (because everyone uses np.get_include() ). A lot of people complain about having to get hacky.
This is the best fix I could come up with: https://github.com/javdrher/GPy/commit/313e35af587fed3f3624733c1022911ea2230067
Its a bit dirty, but assures numpy gets installed prior to executing setup.py

**Comment by mzwiessele** [comment]
I put the setup_requires in. I hope that fixes the issue.

**Comment by jlintusaari** [comment]
Unfortunately, it is still impossible to install our package directly without first installing numpy. I think it would benefit your package as well if you didn't have to install numpy before GPy.
