### ISSUE TITLE
RBF covariance matrices not PSD

### ISSUE THREAD

**Issue by teodecampos** [SheffieldML/GPy#461]
Hi guys,

In the code below:
`import GPy`
`import numpy as np`
`N = 500`
`k=GPy.kern.RBF(input_dim=1,lengthscale=0.2)`
`X = np.linspace(0.05,1.,N)[:,None] # N points evenly spaced over [0,1]`
`C= k.K(X,X)`
`print 100.*(C != C.T).sum()/N**2`

you'll see that almost 20% of the elements of C are different from C.T by a tiny amount, i.e., C is not perfectly symmetric.

Then, even if build a symmetric version of C, using this:
`C2 = np.sqrt(C*C.T) `
it is still not positve semi-definite, i.e., 
`ev = np.linalg.eigvals(C2)`
`print 100.*(ev <= 0).sum()/N`
almost half of the eigenvalues are tiny negative (often complex) numbers.

This is clearly due to machine precision issues, but in only happens with RBF.

I thought this issue would have been solved in #314, but apparently it's not related. 
I'm using the devel branch of GPy, "pulled" today.

**Comment by alansaul** [comment]
Hi Teo,

That is a little odd, you are right they are out by a little bit,

```
abs_diff = abs(np.tril(C) - np.triu(C).T)
print("{}\% of indices are out".format(100*np.sum(abs_diff > 0.0) / float(C.shape[0]**2)))
print("Average out by {}".format(abs_diff[abs_diff > 0.0].mean()))
```

For me suggests that around 10% are out by an average of 1e-16 for me, which is approaching numerical precision, I would have though this was only an issue when the X locations are close to one another, but that doesn't seem to be the case.

It is curious that it isn't an issue for the Matern kernel though, as they are both stationary kernels and so both use the same function for computing distances. My first thought was that it might be a cython issue but it appears to make no difference.

I suspect the issue is within _unscaled_dist of kern/src/stationary.py

Perhaps we can think of a more stable set of operations.

**Comment by alansaul** [comment]
I'm certain it is _unscaled_dist. If you use 
C= k.K(X) 
instead of 
C= k.K(X,X)
then the numerical instability is avoided. So the problem is somewhere in this:
```
            Xsq = np.sum(np.square(X),1)
            r2 = -2.*tdot(X) + (Xsq[:,None] + Xsq[None,:])
            util.diag.view(r2)[:,]= 0. # force diagnoal to be zero: sometime numerically a little negative
            r2 = np.clip(r2, 0, np.inf)
            return np.sqrt(r2)
```

It turns out by changing the line:
            r2 = -2.*np.dot(X, X2.T) + (X1sq[:,None] + X2sq[None,:])
for 
            r2 = -2.*np.dot(X, X2.T) + X1sq[:,None] + X2sq[None,:]
which simply changing the order of the operations, resolves this numerical instability.

**Comment by alansaul** [comment]
I'm certain it is _unscaled_dist. If you use
C= k.K(X)
instead of
C= k.K(X,X)
then the numerical instability is avoided. So the problem is in this:
```
            X1sq = np.sum(np.square(X),1)
            X2sq = np.sum(np.square(X2),1)
            r2 = -2.*np.dot(X, X2.T) + (X1sq[:,None] + X2sq[None,:])
            r2 = np.clip(r2, 0, np.inf)
            return np.sqrt(r2)
```
It turns out by changing the line:
r2 = -2.*np.dot(X, X2.T) + X1sq[:,None] + X2sq[None,:]
for
r2 = -2.*np.dot(X, X2.T) + (X1sq[:,None] + X2sq[None,:])
which simply changing the order of the operations, resolves this numerical instability.

**Comment by teodecampos** [comment]
Yes, that does solve the symmetry problem, thanks Alan!

However it doesn't solve the PSD problem, C still has lots of tiny negative eigenvalues, and the same happens if we use 
`C = k.K(X)`
as 
`np.linalg.eigvals(C)`
returns tiny negative values (in the order of e-14) and complex numbers.
But it looks like this is actually an issue of numerical instability in Numpy's eigen-decomposition (actually LAPACK), as discussed by [Bauckhage, 2015](https://dx.doi.org/10.13140/RG.2.1.2307.5046).

**Comment by mzwiessele** [comment]
Did we fix this?
