### ISSUE TITLE
Online / Incremental updates

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [SheffieldML/GPy#464]
I am very interested in this library. Congrats and thanks for making this available for others to experiment with.

Does the library include support for online updates?

E.g. Say we fit a regression GP to some data `X_original` and `Y_original`.  We later receive additional data points `X_new` and `Y_new`. Does one have to *re-fit* the entire model for all of [`X_original` + `X_new`] and [`Y_original` + `Y_new`]? Or does `GPy` have support for incremetal updates?

**Comment by mzwiessele** [comment]
1: You can add in new data by the add_xy methods. The nature of GPs require you to fit the molehill, but as you are at a optimized state, you can just refit from there with optimize.

2: there is a stochastic variational implementation in svi_gp, which allows for online updates by approximation.

**Comment by amelio-vazquez-reina** [comment]
Thanks @mzwiessele  Re-1 what do you mean by _"the nature of GPs require you to fit the molehill?"_.  Isn't this more a property of the fitting mechanism? Sorry just making sure I understand how it all works here.

E.g. if the default fitting mechanism (using `optimize`) isn't fitting an actual posterior  (and it's instead just getting an MLE estimate instead), one wouldn't be able to update the posterior in the usual Bayesian way, so that would make sense. But if the fitting mechanism estimates the posterior over the parameters, doing online updates should be possible easily through Bayesian updates (maybe that's what `svi_gp` does?).

**Comment by mzwiessele** [comment]
I guess it depends on what we mean by re fitting the model. We just continue the updates from where we already where, so it will take less steroids to arrive at the new optimum. One could do rank one updates on the covariance matrix, but for the new parameter values we need to optimize again. 

The posterior is not tractable and therefore the mle is the only way of fitting the parameters. In case you know the hyper parameters you can compute the posterior directly, so again, it depends on what your model is.

**Comment by alexfeld** [comment]
Hi. Just to follow up on this, is there a way to do a rank one Cholesky update to the GP kernel matrix? I think that's the typical way that additions to the training set are handled. I'm not seeing an `add_xy` method in the documentation so I thought I'd check here first.

**Comment by mzwiessele** [comment]
It is in there, see m.set_xy(x,y) and more, just hit m.set_<tab>

**Comment by alexfeld** [comment]
Ah I see. It looks like this is computing a brand new kernel matrix and Cholesky decomposition every time the data is updated. Is that correct?

**Comment by mzwiessele** [comment]
Indeed. In the utility function there is a rank one update for the EP implementation, if I am not mistaken. Maybe ExpectationPropagation is a good place to start for an implementation of this feature.

**Comment by alexfeld** [comment]
Ok, so please correct me if I'm wrong, but it appears that if you change the data (e.g. by adding a training point) the following things happen
- the inference method is called which computes the new kernel matrix and it's Cholesky decomposition 
- a new `Posterior` object which contains the new Cholesky decomposition and kernel matrix for calculating the posterior values but nothing else

It seems to me that with this workflow, if you want to update `X` to add new training points then there are two options
- save the value of `X` in the `Inference` object and then add a method called `update_inference` to compute the update to the posterior
- modify the existing `inference` method to use the old posterior to compute an update if it exists

Since I'm not familiar with your `paramz` framework, do you think either of these would work or would a different method be better? I would add a method to the `GP` class called `update_XY` that appended new training points to the existing `X` and `Y` vectors/matrices.

The process for the rank 1 update to the Cholesky and kernel is as follows
```python
Knew = [[K(X,X) K(X, xnew)],  
        [K(xnew,X)  K(xnew, xnew)]
u = solve(L,K(X,xnew))
v = chol(K(xnew, xnew) - dot(u.T,u))
Lnew = [[L  0], 
        [u.T v]]
```

The end result would be a function like `util.linalg.pdinv` except `L` is provided instead of `A` and each items would be computed using a rank one update. The other difference is the storage of the old Cholesky inside the `Inference` class instead of just through the `Posterior`. This could be accomplished most easily by adding an input the the `inference` method that takes in an optional `Posterior` instance and then parses that object for the required data. 

What do you think?

**Comment by alexfeld** [comment]
I forgot to mention, this process would require that `GP` be able to differentiate between an update to `X` and a brand new specification of `X`.
