### ISSUE TITLE
Heteroscedastic noise in Sparse GP with variational inference

### ISSUE THREAD

**Issue by ghost** [SheffieldML/GPy#501]
Hello, everyone! I am currently exploring this amazing library as part of my Master's thesis work. At this moment I would like to use the SparseGPRegression class with heteroscedastic noise, but I am not quite sure how to do it the best way.

Additionally I want to set three different noise levels only, because my data has three different sources. This means that all data from the same source would receive the same noise level. I would like to let these three noise levels be learned by the optimization procedure. 

So my question is: in order to implement this, does it make more sense to add a kernel similar to the white heteroscedastic kernel, which would account for all the varying noise levels, or to change the likelihood object to a HeteroscedasticGaussian instead? Looking forward to your hints. :)

**Comment by mzwiessele** [comment]
In a full GP this would amount to the exact same model. In the Sparse GP case, though, it amounts to two slightly different models. 

Using the HeteroscedasticGaussian will add the noise to beta, the noise parameter on the outside and the white noise kernel will add it to the latent function f.

I would try both, as beta is estimated using the inducing inputs as sufficient statistic and the White noise kernel will estimate it from the data directly.

**Comment by gabrielazarzar** [comment]
Thanks a lot for your answer! I would like to pose some additional questions:

- The class SparseGPRegression implements sparse GP with variational inference. Is this implemented as proposed in Titsias, 2009 (http://proceedings.mlr.press/v5/titsias09a/titsias09a.pdf)?

- If so, predictions for unseen data are made by calculating the approximate posterior GP mean as in equation 6 in Titsias, 2009. In this equation, the noise variance appears inside mu, the optimal mean of the variational distribution of the inducing outputs. In case I want to use heteroscedastic noise (using HeteroscedasticGaussian likelihood) in this scenario, equation 6 in Titsias seems to require one noise variance per inducing output (m in total). However the HeteroscedasticGaussian likelihood receives one noise variance per output (n in total). So my question is: in order to use the HeteroscedasticGaussian likelihood for sparse GPs with variational inference, am I forced to set m = n, i.e. the number of inducing variables = the number of data points?

I am surely missing something here. I am looking forward to your hints. :) Many thanks!

**Comment by gabrielazarzar** [comment]
Thanks a lot for your answer, @mzwiessele ! There are however some still unclear things related to the same topic. Here I go:

- The class SparseGPRegression implements sparse GP with variational inference. Is this implemented as proposed in Titsias, 2009 (http://proceedings.mlr.press/v5/titsias09a/titsias09a.pdf)?

- If so, predictions for unseen data are made by calculating the approximate posterior GP mean as in equation 6 in Titsias, 2009. In this equation, the noise variance appears inside mu, the optimal mean of the variational distribution of the inducing outputs. In case I want to use heteroscedastic noise (using HeteroscedasticGaussian likelihood) in this scenario, from equation 10 in Titsias (which shows the expression of mu) I assume that it is necessary to provide one noise variance per inducing output (m noise variances in total). However the HeteroscedasticGaussian likelihood receives one noise variance per output (n noise variances in total). So my question is: in order to use the HeteroscedasticGaussian likelihood for sparse GPs with variational inference, am I forced to set m = n, i.e. the number of inducing variables = the number of data points? This would kill the sparsity. Therefore if you have any suggestion about how I can use HeteroscedasticGaussian likelihood with a SparseGPRegression model and with m < n, I am glad to hear. :)

I am surely missing something here. Looking forward to your hints. :) Many thanks!
