### ISSUE TITLE
Repeated Data Vectors Produce Non-Positive Definite Kernel Matrices

### ISSUE THREAD

**Issue by jdmartin86** [SheffieldML/GPy#523]
I'm not sure if this is a bug; it's more of a deficiency that I've noticed through abusing the library. Either way, I figured that it was an issue worth bringing up. 

Whenever I try to compute a kernel matrix using a dataset with repeated samples, the result will not be  numerically positive definite. Take the following routine for example.

```
import numpy as np
import GPy

X = np.ones( (4,1) )
k = GPy.kern.RBF(input_dim=1, variance=0.001, lengthscale=0.07)
K = k.K(X)
print np.linalg.eigvalsh(K)
```

This will produce Eigenvalues that are numerically different -- some negative.

**Comment by lawrennd** [comment]
Hi John,

I think that's expected behaviour, because placing in two repeated values
will necessarily make the covariance matrix rank deficient (unless a noise
term is added).

The heuristic for dealing with this is sometimes known as 'adding jitter'.
Where you add some diagonal to the matrix to make it numerically positive
definite again.

The covariance matrix you define above should be (if I understood
correctly) rank 1.

I'm expecting that the negative eigenvalues should be very small ... is
that correct?

Neil

**Comment by jdmartin86** [comment]
Hi Neil,

Thanks for the response. Indeed, the covariance will become rank deficient with repeated inputs, and the associated Eigenvalues from GPy covariances are small for the example I provided. For such inputs, however, I expected GPy to throw an exception. Or at a minimum, I expected any jitter heuristic GPy implements to produce strictly positive Eigenvalues.

My post was just intended to document a limitation of the library. However, if this issue falls outside the scope of GPy's failure mitigation plan, then feel free to close it. 

~ John

**Comment by lawrennd** [comment]
Jitter is added if necessary when Cholesky decomposition is done in the GP
code.

I think it's hard to think of adding it pre-emptively because computing the
effective rank needs to be done. So we delay that until inversion is
attempted.
