### ISSUE TITLE
Specifying a polynomial prior mean function

### ISSUE THREAD

**Issue by ISPPrice** [SheffieldML/GPy#524]
Hi

I'm relatively new to GPy so my apologies if this is a trivial question, and apologies if this is the wrong place for the question.

I would like to specify an order 2 or 3 polynomial as the prior mean function, the parameters (coefficients) of which I would like to be learnt along with the standard parameters normally learnt for the posterior.

I have seen how to do this for a linear mean function, as follows:
```
mf = GPy.mappings.linear.Linear(1, 1)
m = GPy.core.GP(X, Y, kernel=kernel, likelihood=lik, mean_function=mf)
```

Is it possible to do this for higher order polynomials?

Thanks

Ilan

**Comment by msbauer** [comment]
Hi Ilan,

This is certainly possible, however, you will have to implement your own mean function for this, which entails writing code for the function as well as for the gradients w.r.t. input and parameters. You can have a look at the code for the linear mean function in GPy.mappings.linear to see how to do this. To check whether your gradients are correct, you can use the in-built check_gradient() function. An example for such a test is provided in GPy.testing.mapping_tests.

**Comment by monabf** [comment]
@ISPPrice did you end up implementing a polynomial mapping? I would like to use one as a prior mean function too, and I was wondering if you had already done the job of implementing it. 

Otherwise, is defining such a mapping the only way to define a non constant prior mean function in GPy? What if I don't especially want to learn the coefficients of the polynomial while enforcing its structure, but instead simply know a prior mean function on top of which I want my "regular" GP to be trained? Is there no simple way of specifying this prior mean then do standard GP regression when I observe data? I just want the "prior mean" term in the standard GP regression equations to be equal to some predefined function, and I don't really see how to set that.

Thanks!

**Comment by msbauer** [comment]
@monabf: Thanks for your question. If you have a predefined mean function and don't want to learn any of its parameters, the easiest way is probably to just subtract it from the data before fitting the GP to it. That is
```y_nomean = y - f_mean(X)```
where `f_mean` is your pre-defined mean function. To make predictions at new input locations you have to add `f_mean(X_new)` to the prediction of the GP, of course.

Hope this helps

**Comment by monabf** [comment]
Thanks for your fast response @msbauer. I had thought of that too, but was trying to figure out whether there was an easy way of specifying the prior mean function directly inside GPy. It doesn't seem like it so I'll do what you propose! Thanks for your help
