### ISSUE TITLE
Different default normalizer arguments.

### ISSUE THREAD

**Issue by ethanluoyc** [SheffieldML/GPy#552]
Hi,

I think that there are differences in the default arguments in GP and GPRegression?
Specifically, from the docs http://gpy.readthedocs.io/en/deploy/GPy.core.html GP has normalizer set default to False whereas in GPRegression it is set to None (Also in SparseGPR), I am not sure whether this is the intended behavior and in my use case I need to specify the normalizer in my constructor specifically to make things work. 

This might be related https://github.com/SheffieldML/GPy/issues/119.

**Comment by mzwiessele** [comment]
Good spotting. The Models in the models sub package are convenience classes to enhance user experience. Over the course of development an abundance of issues arouse of ppl not being able to fit data using GPy, while being able to fit it with same parameter initializations on other frameworks. We found out that most of them were due to normalization done in other packages, whereas in GPy, we wanted to present the raw GP functionality and for the user to decide what to do with their data. This is the core GP class. After experiencing the issues, we developed the convenience functionality in the models module to circumvent such difficulties.

If you want different standard parameter initializations in your own copy, I'd suggest you implement a small package for yourself, in which you build upon the standard initializations of parameters and set the ones you want for yourself.

Hope that explains things!
