### ISSUE TITLE
Optimizing the GPRegression over a single parameter

### ISSUE THREAD

**Issue by yenicelik** [SheffieldML/GPy#623]
I am aware that one can optimize over all parameters using the `GPRegression.optimize()` function, which optimizes over the `objective_function()` (at least, this is what I've understood so far).

However, is it possible to *optimize over only a certain parameter*, such as the length scale, or the variance of a kernel for example? And if not, how would I best accomplish this? Any help is greatly appreciated.

**Comment by mzwiessele** [comment]
Just fix all parameters you do *not* wish to optimize over.

`m.kern.lengthscale.fix()` 

Or similar should do the trick.

**Comment by yenicelik** [comment]
Thanks a lot for the quick reply! :) Is there a docs page / source code page for .fix()? Also, can I `unfix` those parameters again, after I have optimized the desired one?

More specifically, what I wish to do is iteratively optimize one parameter, and then the other, so I need to keep one fixed, and then the other (and repeat this procedure).

**Comment by mzwiessele** [comment]
http://paramz.readthedocs.io/en/master/paramz.html#paramz.parameterized.Parameterized <http://paramz.readthedocs.io/en/master/paramz.html#paramz.parameterized.Parameterized>

or

http://paramz.readthedocs.io/en/master/paramz.core.html#module-paramz.core.constrainable <http://paramz.readthedocs.io/en/master/paramz.core.html#module-paramz.core.constrainable>

The docs are a bit scattered because of the object oriented hierarchy. 

Have a flick through, you’ll get there: http://paramz.readthedocs.io/en/latest/paramz.html <http://paramz.readthedocs.io/en/latest/paramz.html>
