### ISSUE TITLE
Question about performance RMSE 

### ISSUE THREAD

**Issue by andreacavalli** [SheffieldML/GPy#624]
Hello,
I have run some experiments in order to collect five different data sets. Each data set has a subset in which data are flagged with a letter.
I have created a test set that contains 10000 random values.

Then I have trained ten Gaussian Processes (using  a data set or a subset as the train set): the kernel is GPy.kern.RBF(input_dim=4, variance=1., lengthscale=1.), the model is GPRegression and at the end I have optimized the model by running model.optimize(). 
After the training, for each GP I have calculated the performance RMSE on the test set.

The question is about the results I have found: is it normal that, for each experiment, the performance RMSE of the whole set is always greater than the performance RMSE of its subset? Is it common that this happens? 
Specifically, sets and their subsets have this number of elements:
- Set 1: 4590, subset 1: 1670
- Set 2: 8849, subset 2: 1670
- Set 3: 2552, subset 3: 980
- Set 4: 5538, subset 4: 980
- Set 5: 2911, subset 5: 496.

Thank you for the answer.

**Comment by adamian** [comment]
Are the subsets selected *randomly* from the bigger set?

**Comment by andreacavalli** [comment]
No, I collect data in two different ways: I collect flagged data by following a given algorithm and I collect unflagged data every 10 seconds.

**Comment by adamian** [comment]
Then the sets and the subsets have different statistics, right? So I can't see the reason why the performance from learning on them shouldn't differ, unless I'm missing something.

**Comment by andreacavalli** [comment]
Exactly, that's the reason of my question. I'm missing something too.

**Comment by andreacavalli** [comment]
Tipically, the RMSE on the error of the whole dataset should be better than the RMSE on the error of a subset. But I got the opposite result and I don't know why.

**Comment by adamian** [comment]
It's difficult to tell without knowing what your specific dataset looks like, but in the general case of having datasets with different statistics it's absolutely possible to get worse results in the bigger dataset (for example, the bigger dataset can be more noisy by nature due to how it's generated). 

With respect to things you do control, check whether your initialization favors the small dataset(s). Check, for example, what happens if you initialize the lengthscale with a larger or smaller value (biasing towards a more or less linear model). Another idea is to try to normalize the big/small data in a consistent way so that you make sure that the initialization doesn't favor the statistics of the smaller dataset (e.g. try to zero-mean the data and maybe scale the std to 1 or try to set the Gaussian_noise.variance to something like 1/100 of the empirical variance of the outputs in each case).
