### ISSUE TITLE
Coregionalized GP predict documentation (multiple inputs)

### ISSUE THREAD

**Issue by janvanrijn** [SheffieldML/GPy#633]
I am a little bit confused how to invoke the predict method of the GPCoregionalizedRegression Model. 

[This notebook](https://bigaidream.gitbooks.io/subsets_ml_cookbook/content/bayes/gp/coregionalized_regression_gpy.html) refers to an extended input format, where the input array of dimensions (num_observations) is extended with an additional column of ones, so we now have an input of shape (num_observations, 2). What does this second column refer to? The task index? Most importantly, how does this generalize to having multiple inputs? (i.e., the tasks have multiple columns in the X array). 

As the Coregionalized GP inherits the predict method from the GP core module, the documentation is unfortunately not up to date (It says `The points at which to make a prediction :type Xnew: np.ndarray (Nnew x self.input_dim)`). 

Unfortunately, the [examples module](http://gpy.readthedocs.io/en/deploy/_modules/GPy/examples/regression.html#coregionalization_toy) doesn't use multiple inputs nor the predict method so this didn't help either. 

Any help would be greatly appreciated, I'd be happy to create a PR with an additional for the examples module once this is resolved.

**Comment by janvanrijn** [comment]
According [to this issue](https://github.com/SheffieldML/GPy/issues/376), it apparently works when I add an additional dimension to the input (telling from which input the x values came). 

Implicitly, this means that for a given output (which is specified by output_index, right?) I can insert data from an arbitrary input? I can even give it data coming from various different input sources (e.g., for a given data point x, feature 1 comes from task 2, feature 2 from task 3, etc). Is this intentional?

**Comment by lionfish0** [comment]
Hello,
As you've discovered, the last column* of the input matrix X refers to the
'region', so you can, indeed, specify in a random order where each element
of Y came from.
For example if you have two temperature gauges, you could imagine the first
column of X is the time, and the second the index of the temperature
gauge**:
X = np.array([[3,0],[6,1],[9,0],[12,0],[3,1],[6,0],[12,1]]
Y = np.array([[2,6,4,6,4,3,11]].T

So output_dim=2.

I'm not familiar with the GPCoregionalisedRegression object, I do my
coregionalisation by combining kernels and calling the normal GPRegression
function - maybe I'm missing something? (does the
GPCoregionalisedRegression method do something more efficient with the
covariance structure? Hopefully someone else can elaborate on that)

E.g for the example above.

kern = GPy.kern.RBF(1)**GPy.kern.Coregionalize(input_dim=1,output_dim=2,
rank=1)m = GPy.models.GPRegression(X,Y,kern)

I wrote a tutorial about it - that will eventually go into the docs for GPy
- Alan espeically spent a lot of time getting the documentation better, and
it's all sitting in a repo ready to be turned into a website -
unfortunately the RSE who was going to do this step is leaving today!
Here's the python notebook anyway:
https://github.com/SheffieldML/notebook/blob/deploy/GPy/multiple_outputs/Introduction%20to%20Multiple%20Output%20Gaussian%20Processes.ipynb
It's not been checked for correctness yet - hopefully someone can
feedback/pull request/push fixes.

Mike.

* It's actually I think* the last column that hasn't been used*, or
something (as mentioned in the issue you linked to - there's a bug in
there, but I never got to the bottom of it).
** I think it's important that the region column's elements are no less
than zero, and no greater than output_dim-1.

**Comment by janvanrijn** [comment]
Dear Mike, 

Thanks for your quick response! The answer is totally clear, but I think I posed the question poorly. 

> For example if you have two temperature gauges, you could imagine the first column of X is the time, and the second the index of the temperature gauge**:
> X = np.array([[3,0],[6,1],[9,0],[12,0],[3,1],[6,0],[12,1]] 
> Y = np.array([[2,6,4,6,4,3,11]].T So output_dim=2.

This also is an example where the base task (mapping from time to temperature) has one feature (i.e., time) which becomes a 2-feature problem in the multi-task setting. Now suppose that my base task is also has multiple features, for example I want to predict based on length and age what grade for gym someone will obtain, and there are two teachers (two tasks) handing out grades. 

Based on your answer, I would infer that the X array should be of shape (num_observations_accross_teachers, 3), where the first column is age, second column is length and the third column is teacher id. Furthermore, input_dim = 2 and output_dim = 2? Can you confirm whether this is correct?

To me it is not entirely clear from the documentation and examples how to handle the multiple input/multiple output cases (maybe I'm just bad at reading), but I'd be happy to contribute an example if my assumptions above are correct and if that would help. 

Jan

**Comment by janvanrijn** [comment]
I took the liberty of slightly adapting your code to a MWE that suits my needs:
```
import numpy as np
import GPy

X = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
Y = np.array([[0, 0, 1, 0, 1, 0, 1, 1]]).T

print(X.shape)  # (8, 3) --> 8 examples, first column is age, second column is length, third column indicates the teacher
print(Y.shape)  # (8, 1)
num_tasks = 2
num_obs, num_feats = X.shape
num_feats -= 1  # important, because the last column indicates the "task"

kern = GPy.kern.RBF(1) ** GPy.kern.Coregionalize(input_dim=num_feats, output_dim=num_tasks, rank=1)
m = GPy.models.GPRegression(X, Y, kern)

print('Start optimizing')
m.optimize()
print('Done optimizing')
```
This all seems to work perfectly fine. However, when I want to add predictions on the train set, it crashes with the following error:
```
m.predict(X)
```

```
Traceback (most recent call last):
  File "/home/janvanrijn/projects/openml-multitask/examples/test.py", line 20, in <module>
    m.predict(X)
  File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python3.6/site-packages/GPy/core/gp.py", line 323, in predict
    mean, var = self._raw_predict(Xnew, full_cov=full_cov, kern=kern)
  File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python3.6/site-packages/GPy/core/gp.py", line 280, in _raw_predict
    mu, var = self.posterior._raw_predict(kern=self.kern if kern is None else kern, Xnew=Xnew, pred_var=self._predictive_variable, full_cov=full_cov)
  File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python3.6/site-packages/GPy/inference/latent_function_inference/posterior.py", line 286, in _raw_predict
    Kxx = kern.Kdiag(Xnew)
  File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python3.6/site-packages/GPy/kern/src/kernel_slice_operations.py", line 94, in wrap
    ret = f(self, s.X, *a, **kw)
  File "<decorator-gen-20>", line 2, in Kdiag
  File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python3.6/site-packages/paramz/caching.py", line 283, in g
    return cacher(*args, **kw)
  File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python3.6/site-packages/paramz/caching.py", line 172, in __call__
    return self.operation(*args, **kw)
  File "/home/janvanrijn/anaconda3/envs/openml-multitask/lib/python3.6/site-packages/GPy/kern/src/prod.py", line 63, in Kdiag
    return reduce(np.multiply, (p.Kdiag(X) for p in which_parts))
ValueError: operands could not be broadcast together with shapes (8,) (16,) 
```

**Comment by ric70x7** [comment]
Hello,

Here is a script that runs both cases: Regression and
CoregionalizedRegression

import numpy as np
import GPy

X = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0,
1], [1, 1, 0], [1, 1, 1]])
Y = np.array([[0, 0, 1, 0, 1, 0, 1, 1]]).T

print(X.shape)  # (8, 3)
print(Y.shape)  # (8, 1)
num_tasks = 2
num_obs, num_feats = X.shape
num_feats -= 1  # important, because the last column indicates the "task"

# Using GPRegression
kern = GPy.kern.RBF(2) ** GPy.kern.Coregionalize(input_dim=1,
output_dim=num_tasks, rank=1) # The RBF is the one that has 2 inputs,
Coregionalized  works on the output-index dimension
m0 = GPy.models.GPRegression(X, Y, kern)
m0.optimize()
m0.predict(X)

# Using ICM (there is also an LCM option if you need to pass a list of base
kernels)
lcm1 = GPy.util.multioutput.ICM(input_dim=2,num_outputs=2, kernel=kern)
m1 = GPy.models.GPRegression(X, Y, lcm1)
m1.optimize()
m1.predict(X)

# Using GPCoregionalizedRegression
lcm2 = GPy.util.multioutput.ICM(input_dim=2,num_outputs=2,
kernel=GPy.kern.RBF(2))

# The inputs are lists of input-output, without the artificial feature
added as the third column
X_list = [X[X[:,2]==i, :2] for i in range(2)]
Y_list = [Y[X[:,2]==i] for i in range(2)]

m2 = GPy.models.GPCoregionalizedRegression(X_list, Y_list, kernel=lcm2)
m2.optimize()

new_X = X # In this case the input is not a list, but an array and it
includes the third column with the index
m.predict(new_X,Y_metadata={'output_index':np.ones((new_X.shape[0],1)).astype(int)})
# Predicitions need us to tell which noise model we are using (again an
output index per point)
m.predict(new_X,Y_metadata={'output_index':np.zeros((new_X.shape[0],1)).astype(int)})
# the output_index doesn't need to be all zeros or ones, it can be a
combination. But it has to be a combination of zeros or ones (ie the
outputs used to train the model).

# Some notes:
# 1) The difference between using GPRegression with with an ICM/LCM kernel
vs GPCoregionalized Regression:
# The first one assumes the noise variance is the same for both outputs,
the latter assumes noise is different for each one.
# Have a look at print(m1) vs print(m2).
#
# This is important becasue at some point we were aiming to have different
noise models for the different outputs,
# for example, one output could be Gaussian and the other could be
Bernoulli (I like a lot that idea!).

# 2) It is confusing that GPCoregionalized uses lists with two-columns
arrays, but the prediction uses arrays with 3-columns.
# Yes, that is an issue that probably needs to change.

# 3) It is also confusing that we need to pass a metadata with the
output_index if we are already
# stacking the third column to X. Yes, but again this framework was being
developed to allow the combination of
# different noise models. The noise class is handled by the Likelihood
object, while the output correlation is handled by
# the kernel, but they are independent from each other. So in the end this
redundancy was needed.

I hope this helps.

Ricardo

**Comment by janvanrijn** [comment]
Hi Ricardo, 

> The RBF is the one that has 2 inputs, Coregionalized works on the output-index dimension

Ouch, rookie mistake. Thanks for pointing this out!

> 1) The difference between using GPRegression with with an ICM/LCM kernel vs GPCoregionalized Regression: The first one assumes the noise variance is the same for both outputs, the latter assumes noise is different for each one. Have a look at print(m1) vs print(m2).

Duly noted. 

> 2) It is confusing that GPCoregionalized uses lists with two-columns arrays, but the prediction uses arrays with 3-columns. 
> Yes, that is an issue that probably needs to change.

(Not my exact wording) Initially I couldn't see how the 1D case generalized to a N-D case. Now I do it completely makes sense. 

Thanks again for posting this example. From my POV this issue can be closed.
